{
 "title": "Raspberry Pi System Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter\"} - node_boot_time_seconds{job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{device=\"/dev/root\", mountpoint=\"/\"}/node_filesystem_size_bytes{device=\"/dev/root\", mountpoint=\"/\"} * 100)"
    }
   ]
  },
  {
   "title": "File System Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\", mountpoint=\"/\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\", mountpoint=\"/\"} - node_filesystem_avail_bytes{device=\"/dev/root\", mountpoint=\"/\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\", mountpoint=\"/\"}",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Current CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "CPU Temperature Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{job=\"node_exporter\"})",
     "legendFormat": "CPU Temperature"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Usage Monitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes{job=\"node_exporter\"} - node_memory_Buffers_bytes{job=\"node_exporter\"} - node_memory_Cached_bytes{job=\"node_exporter\"} - node_memory_SReclaimable_bytes{job=\"node_exporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node_exporter\"}",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}